approval_policy = "never"
sandbox_mode = "danger-full-access"
# tool_output_token_limit = 5_000
model = "gpt-5.2"
model_reasoning_effort = "high"
suppress_unstable_features_warning = true
review_model = "gpt-5.2-codex"
web_search = "live"
personality = "pragmatic"

[default]
model = "gpt-5.2-codex"
model_reasoning_effort = "medium"

[profiles.deep-review]
model = "gpt-5-pro"
model_reasoning_effort = "high"
approval_policy = "never"

[features]
rmcp_client = true
unified_exec = true
shell_snapshot = true
steer = true
collab = true

collaboration_modes = true
[projects."/Users/ianwatts/.config/ruler"]
trust_level = "trusted"

[projects."/Users/ianwatts/code_projects/social-glass"]
trust_level = "trusted"

[projects."/Users/ianwatts/code_projects/life-project"]
trust_level = "trusted"

[projects."/Users/ianwatts"]
trust_level = "trusted"

[projects."/Users/ianwatts/code_projects/thirtymilezone"]
trust_level = "trusted"

[projects."/Users/ianwatts/code_projects/ambassco-website"]
trust_level = "trusted"

[mcp_servers.RepoPrompt]
command = "/Users/ianwatts/RepoPrompt/repoprompt_cli"
enabled = false
tool_timeout_sec = 1000.0

[mcp_servers.morph-mcp]
command = "npx"
args = ["-y", "@morphllm/morphmcp"]

[mcp_servers.morph-mcp.env]
ENABLED_TOOLS = "edit_file,warpgrep_codebase_search"

[mcp_servers.openaiDeveloperDocs]
url = "https://developers.openai.com/mcp"

[notice]
hide_full_access_warning = true
hide_gpt5_1_migration_prompt = true
"hide_gpt-5.1-codex-max_migration_prompt" = true

  [notice.model_migrations]
  "gpt-5.2" = "gpt-5.2-codex"
