approval_policy = "never"
sandbox_mode = "danger-full-access"
model = "gpt-5.1-codex-max"
model_reasoning_effort = "xhigh"
model_reasoning_summary = "detailed"
model_verbosity = "high"
tool_output_token_limit = 5000

[default]
model = "gpt-5.1-codex-max"
model_reasoning_effort = "medium"

[features]
rmcp_client = true
web_search_request = true

[projects."/Users/ianwatts/code_projects/social-glass"]
trust_level = "trusted"

[projects."/Users/ianwatts/code_projects/life-project"]
trust_level = "trusted"

[projects."/Users/ianwatts"]
trust_level = "trusted"

[projects."/Users/ianwatts/code_projects/thirtymilezone"]
trust_level = "trusted"

[projects."/Users/ianwatts/code_projects/ambassco-website"]
trust_level = "trusted"

[mcp_servers.RepoPrompt]
command = "/Users/ianwatts/RepoPrompt/repoprompt_cli"
args = []
enabled = false
tool_timeout_sec = 1000
tool_output_token_limit = 25000

[mcp_servers.context7]
url = "https://mcp.context7.com/mcp"
http_headers = { "CONTEXT7_API_KEY" = "ctx7sk-0139fb80-69c6-4426-a731-c438b05438c4" }

[mcp_servers.deepwiki]
command = "npx"
args = ["-y", "mcp-remote@latest", "https://mcp.deepwiki.com/sse"]

[notice]
hide_full_access_warning = true
hide_gpt5_1_migration_prompt = true
"hide_gpt-5.1-codex-max_migration_prompt" = true

[profiles.planning.mcp_servers.notion]
url = "https://mcp.notion.com/mcp"
enabled_tools = ["notion-create-comment", "notion-create-pages", "notion-fetch", "notion-get-comments", "notion-get-self", "notion-search", "notion-update-database", "notion-update-page"]
# disabled_tools = ["notion-create-comment", "notion-create-database", "notion-create-pages", "notion-duplicate-page", "notion-fetch", "notion-get-comments", "notion-get-self", "notion-get-teams", "notion-get-user", "notion-get-users", "notion-list-agents", "notion-move-pages", "notion-search", "notion-update-database", "notion-update-page"]